# Generated by Django 5.2 on 2025-04-25 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('validade', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga')], default='ABERTA', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='transacoes.cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('POUPANCA', 'Poupança'), ('CDB', 'CDB'), ('TESOURO', 'Tesouro Direto'), ('ACOES', 'Ações'), ('FUNDOS', 'Fundos de Investimento')], default='POUPANCA', max_length=20)),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rendimento', models.DecimalField(decimal_places=2, help_text='Taxa de rendimento anual em %', max_digits=5)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_resgate', models.DateField(blank=True, null=True)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_resgate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='transacoes.investimento')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=200)),
                ('estabelecimento', models.CharField(max_length=100)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='transacoes.cartao')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='transacoes.fatura')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('PIX', 'Pix'), ('TED', 'TED'), ('DOC', 'DOC')], default='PIX', max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
