# Generated by Django 5.2 on 2025-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='bandeira',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('ELO', 'Elo'), ('AMEX', 'American Express')], default='VISA', max_length=20),
        ),
        migrations.AddField(
            model_name='cartao',
            name='dia_vencimento',
            field=models.IntegerField(default=10),
        ),
    ]
