name: Build and deploy Python app to Azure Web App - Ourbank

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

     
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Cleaning testing files
        run: |
          rm -f db.sqlite3


      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5A89125A0F8447169D05DBACA9F05DDF }}
           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_702EDB95A98644F0BEA4E7EF76482391 }}
           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62DADD52245D417294192B0EAE0C96BF }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Ourbank'
          slot-name: 'Production'
          
